yii2/app/modules/service/controllers/DocStorageController.php
<?php

namespace app\modules\service\controllers;

use Yii;
use app\modules\service\components\Controller;
use common\components\DocStorage;
use yii\helpers\Url;

/**
 * OpportunityController
 */
class DocStorageController extends Controller
{
    public function actionIndex()
    {
        if (!DocStorage::isEnabled()){
            return $this->redirect(Url::to(['/service']));
        }

        return $this->render('index');
    }
}

yii2/app/modules/service/controllers/OpportunityController.php
<?php

namespace app\modules\service\controllers;

use Yii;
use app\modules\service\components\Controller;
use common\components\OpportunityTracker;
use yii\helpers\Url;

/**
 * OpportunityController
 */
class OpportunityController extends Controller
{
    public function actionIndex()
    {
        if (!OpportunityTracker::isEnabled()) {
            return $this->redirect(Url::to(['/service/opportunity-marketing']));
        }

        return $this->render('index');
    }
}

yii2/app/modules/service/controllers/OpportunityMarketingController.php
<?php

namespace app\modules\service\controllers;

use Yii;
use app\modules\service\components\Controller;

/**
 * OpportunityMarketingController
 */
class OpportunityMarketingController extends Controller
{
    public function actionIndex()
    {
        $this->titlePage = "Opportunity marketing";

        return $this->render('index');
    }

}

yii2/app/modules/service/controllers/ServiceController.php
<?php

namespace app\modules\service\controllers;


use Yii;
use app\modules\service\components\Controller;
use common\components\OpportunityTracker;
use common\components\DocStorage;
use app\models\OpportunityLicenseForm;
use yii\helpers\Url;

/**
 * ServiceController
 */
class ServiceController extends Controller
{
    public function actionIndex()
    {
        $opportunityEnabled = OpportunityTracker::isEnabled();
        $docStorageEnabled = DocStorage::isEnabled();

        return $this->render('index',[
            'opportunityEnabled'=> $opportunityEnabled,
            'docStorageEnabled' => $docStorageEnabled
        ]);
    }

    public function actionTrackerLicense()
    {
        $model = new OpportunityLicenseForm();
        $this->titlePage = "Opportunity Tracker Agreement";

        return $this->render('tracker-license', [
            'model' => $model,

        ]);
    }

    public function actionTrackerTraining()
    {
        $model = new OpportunityLicenseForm();
        $request = Yii::$app->request;
        $flow = $request->post('OpportunityLicenseForm');


        if (count($flow)==0){
            return $this->redirect(Url::to(['/service']));
        }
        $this->titlePage = "Opportunity Tracker Training";

        return $this->render('tracker-training', [
            'model' => $model,
            'flow'  => $flow["flow"]
        ]);
    }

    public function actionTrackerEnable()
    {
        $request = Yii::$app->request;
        $flow = $request->post('OpportunityLicenseForm');

        if (count($flow)>0) {
            if (OpportunityTracker::Enable($flow["flow"])){
                return $this->redirect(Url::to(['/service/opportunity']));
            }
            else {
                return $this->redirect(Url::to(['/service']));
            }
        }
        else {
            return $this->redirect(Url::to(['/service']));
        }
    }

    public function actionTrackerDisable()
    {
        OpportunityTracker::Disable();
        return $this->redirect(Url::to(['/service']));
    }

    public function actionDocStorageLicense()
    {
        $model = new OpportunityLicenseForm();
        //$this->titlePage = "eDocument Storage Agreement";
        $this->view->title ="eDocument Storage Agreement";

        return $this->render('doc-storage-license', [
            'model' => $model,
        ]);
    }

    public function actionDocStorageEnable()
    {
        DocStorage::Enable();
        return $this->redirect(Url::to(['/service']));
    }

    public function actionDocStorageDisable()
    {
        DocStorage::Disable();
        return $this->redirect(Url::to(['/service']));
    }
}

yii2/app/modules/service/views/service/doc-storage-license.php
<?php
    use yii\bootstrap\Modal;
    use yii\widgets\ActiveForm;
    use yii\helpers\Url;
    use yii\helpers\Html;
?>
<div class="row">
    <div class="col-md-10">
        <p>
            Welcome to SageFire's eDocument Storage!  We are excited to get you started.
        <p>
            eDocument Storage provides a very efficient method for <?=Yii::$app->params['companyName']?> subscribers to follow-up with their prospects and customers,
            and maximize their business opportunities.  It's simple! Import the scanned image of your receipt or document from your computer and link it
            to your specific transaction.
        </p>
        <p>
            Just like Opportunity Tracker, each transaction can be linked to a specific transaction. As an example, if you
            have an extraordinary expense associated with a large sales meeting, import the receipt, a photo of your group, and the original letter
            of invitation, and link them together using eDocument Storage.
        </p>
        <p>
            During the Beta Release, please keep your original receipts as additional back-up.  Because this is a Beta release, please be aware that
            the layout or formatting of this system could change at any moment.  If you see anything you would like changed, encounter any strange
            behavior, or would like to give us a praise, please feel free to give us feedback!
        </p>
        <p>
            Once turned on, eDocument Storage is embedded within your <?=Yii::$app->params['companyName']?> account, and a centralized eDocument Storage module
            within Premium Services.
        <p>
            <b>Next</b>, please read and agree to the <?=Yii::$app->params['companyName']?> License Agreement.
            <?php
            Modal::begin([
                'header' => '<h2>'.Yii::$app->params['companyName'].' License Agreement</h2>',
                'toggleButton' => [
                    'label' => 'Read it here',
                    'class' => 'btn btn-primary'
                ],
                'options' =>['class' => 'license-text']
            ]);

            echo Yii::$app->controller->renderPartial('_license');

            Modal::end();
            ?>
        </p>
        <p>
            By clicking "I Agree", you agree to all terms and conditions.
            <?php
            $form = ActiveForm::begin([
                'action' => Url::to(['doc-storage-enable'])
            ]);
            echo Html::submitButton('I Agree', [
                'class' => 'btn btn-success'
            ]);
            $form::end();
            ?>
        </p>
    </div>
    <div class="col-md-2">
        <img align=right src="/images/dollarguy.jpg" height="300px">
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <br>
        <a href="<?= Url::to([$this->context->getHomeUrl()]) ?>">No Thanks. Take me to Premium Services.</a>
    </div>
</div>

yii2/app/modules/service/views/service/index.php
<?php
    use yii\helpers\Url;
    use yii\helpers\Html;
?>
<h2>Opportunity Tracker</h2>
<div class="row">
    <div class="col-md-1">
        <a href="<?= Url::to([$this->context->getHomeUrl().'/tracker']) ?>"><img alt='Opportunity Tracker' src='/images/opp.gif' border=0 align=left></a>
    </div>
    <?php
    if (!$opportunityEnabled) {
    ?>
    <div class="col-md-11">
        Don't miss out on the impact of Opportunity Tracker on your business. Rapidly track your contacts, send thank you emails, and get reminders to make your follow-ups.
        <a href="<?= Url::to([$this->context->getHomeUrl().'/opportunity-marketing']) ?>">Learn More</a>
        <p>
            I want the Opportunity Tracker!<img src="/images/c.gif" width=10 height=0><a href="<?= Url::to(['service/tracker-license']) ?>">
            <img src="/images/activate.gif" border="0" align="top"></a>
        </p>
    </div>
    <?php }
    else  {
     ?>
        <div class="col-md-11">
            <i>Your Opportunity Tracker is active!</i> &nbsp;&nbsp; <a href="<?= Url::to([$this->context->getHomeUrl().'/opportunity']) ?>">Take me there</a><br>
            <?php
                echo Html::beginForm(['tracker-disable']) . Html::submitButton('Turn it off!', [
                        'class' => 'btn btn-success',
                        'data-confirm' => 'Turning off your Opportunity Tracker will result in the loss of your current contacts and past history.
                                           Click "OK" if you want to continue to turn it off this service.'
                    ]) . Html::endForm();
            ?>
        </div>
    <?php
    }
    ?>
</div>
<div class="row">
    <div class="col-md-12>">
        <hr>
    </div>
</div>
<h2>Direct eBay Transaction Import</h2>
<div class="row">
    <div class="col-md-1">
        <a href="#" onclick="window.open('/app/import/index.php','import','top=80,left=80,width=825,height=450,scrollbars=yes,resizable=yes');">
            <img alt='Import Transactions' src='/images/ebay.gif' border=0 align=left width="64px">
        </a>
    </div>
    <div class="col-md-11">
        <?=Yii::$app->params['companyName']?> makes it simple to <i>know</i> your eBay business. Rapidly import all eBay bought or sold items...&nbsp;&nbsp;
        <a href="#" onclick="window.open('/app/import/index.php','import','top=80,left=80,width=825,height=450,scrollbars=yes,resizable=yes');">Take me there</a>
    </div>
</div>
<div class="row">
    <div class="col-md-12>">
        <hr>
    </div>
</div>
<h2>eDocument Storage - Now Available in Beta - Activate Below</h2>
<div class="row">
    <div class="col-md-1">
        <img alt='eDocument Storage' src='/images/dsOn.gif' border=0 align=left>
    </div>
    <?php
    if (!$docStorageEnabled) {
    ?>
    <div class="col-md-11">
        <p>
            Is your receipt management driving you crazy? Can't keep track of all your receipts? Is your office a paper forest?
        </p>
        <p>
            No more faded receipts, no more lost receipts! No more receipt management headaches!
        </p>
        <p>
            It's simple! Import the scanned image of your receipt or document from your computer and link it to your specific transaction.
            Just like Opportunity Tracker, each transaction can be linked to a specific transaction. As an example, if you have an
            extraordinary expense associated with a large sales meeting, import the receipt, a photo of your group, and the original letter
            of invitation, and link them together using eDocument Storage. During the Beta Release, please keep your original receipts as
            additional back-up.
        </p>
        <p>
            We want you to use eDocument Storage in any way that it helps you be more successful, and we would like to hear how it has
            uniquely helped your business. During the Beta Release, please email us and keep us advised. Remember, we are in the business
            of making you more efficient in managing your small business.
        </p>
        <p>
            <ul>
                <li> Expense receipts </li>
                <li> Marketing flyers, documents, or a resume </li>
                <li> Logo of your prospective client or of a joint promotion </li>
                <li> A special photo of your team or your kids </li>
                <li> Your incorporation documents or an important written contract </li>
            </ul>
        </p>
        <p>
            Simply upload and safely store your files and documents in eDocument Storage!
        <p/>
        <p>
            I want eDocument storage!<img src="/images/c.gif" width=10 height=0>
            <a href="<?= Url::to(['service/doc-storage-license']) ?>">
                <img src="/images/activate.gif" border="0" align="top">
            </a>
        </p>
    </div>
    <?php }
        else {
    ?>
    <div class="col-md-11">
        <i>Your eDocument storage service is already active!</i>&nbsp;&nbsp; <a href="<?= Url::to([$this->context->getHomeUrl().'/doc-storage']) ?>">Take me there</a>
        <?php
        echo Html::beginForm(['service/doc-storage-disable']) . Html::submitButton('Turn it off!', [
                'class' => 'btn btn-success',
                'data-confirm' => 'Turning off your eDocument Storage will result in the loss of your current stored documents.
                                   Click "OK" if you want to continue to turn it off this service.'
            ]) . Html::endForm();
        ?>

    </div>
    <?php
        }
    ?>
</div>
<div class="row">
    <div class="col-md-12>">
        <hr>
    </div>
</div>
<h2>Full Tax Services!!</h2>
<div class="row">
    <div class="col-md-12">
        Apply for our QuickStart Program to get started fast and eliminate the backlog of your business transactions.  What a relief to be completely caught up and have your <?=Yii::$app->params['companyName']?> account set up for your particular business.
        <p>Leverage the knowledge and experience of small business accountants who are here to help you maximize your business profits.  From tax returns to business advice to bullet proofing your business, our accountants are here to help!
        <p>To learn more contact us at <a href="mailto:<?=Yii::$app->params['supportEmail']?>"><?=Yii::$app->params['supportEmail']?></a>.</p>
    </div>
</div>

yii2/app/modules/service/views/service/tracker-license.php
<?php
    use yii\helpers\ArrayHelper;
    use yii\widgets\ActiveForm;
    use kartik\select2\Select2;
    use common\models\backend\OpportunityFlow;
    use yii\helpers\Html;
    use yii\bootstrap\Modal;
    use yii\helpers\Url;
?>
<div class="row">
    <div class="col-md-10">
        <p>
            Welcome to SageFire's Opportunity Tracker!  We are excited to get you started.
        </p>
        <p>
            Opportunity Tracker provides a very efficient method for <?=Yii::$app->params['companyName']?> subscribers to follow-up with their prospects and customers,
            and maximize their business opportunities.  Opportunity Tracker is designed to make you much more efficient, and therefore give you significantly more selling time.
            When you use your automobile to visit a prospect, or incur business transactions during a visit with your customers, that individual will be listed as an Opportunity.
            Opportunities are then linked to the specific miles driven or specific business transactions, and that is where Opportunity Tracker takes over.
        </p>
        <p>
            Once turned on, Opportunity Tracker is embedded within your <?=Yii::$app->params['companyName']?> account, and a centralized Opportunity Tracker module within Premium Services.
        </p>
    </div>
    <div class="col-md-2">
        <img src="/images/dollarguy.jpg" height="300px" align="right">
    </div>
</div>
<p>
    <b>To get started</b>, please select the Sales Process Flow you wish to install:

    <?php
        $form = ActiveForm::begin([
            'action' => Url::to(['tracker-training'])
        ]);
    ?>
    <div class="row">
        <div class="col-md-6">
        <?php
            echo $form->field($model, 'flow')
                ->label(false)
                ->widget(Select2::classname(), [
                    'data' => ArrayHelper::map(OpportunityFlow::getAll(), 'name', 'description'),
                    'options' => ['placeholder' => 'Select the Flow'],
                ]);
        ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            Next, please read and agree to the KeepMore.net License Agreement.
            <?php
            Modal::begin([
                'header' => '<h2>'.Yii::$app->params['companyName'].' License Agreement</h2>',
                'toggleButton' => [
                                    'label' => 'Read it here',
                                    'class' => 'btn btn-primary'
                                   ],
                'options' =>['class' => 'license-text']
            ]);

            echo Yii::$app->controller->renderPartial('_license');

            Modal::end();
            ?>

        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            By clicking "I Agree", you agree to all terms and conditions.
        </div>
    </div>
    <?php
        echo Html::submitButton('I Agree', [
            'class' => 'btn btn-success'
        ]);
        $form::end();
    ?>
    <div class="row">
        <div class="col-md-12">
            <br>
            <a href="<?= Url::to([$this->context->getHomeUrl()]) ?>">No Thanks. Take me to Premium Services.</a>
        </div>
    </div>

yii2/app/modules/service/views/service/tracker-training.php
<?php
    use yii\helpers\Url;
    use yii\widgets\ActiveForm;
    use yii\helpers\Html;
?>
<p>
    <b>Please carefully read</b> through the following information and training for Opportunity Tracker.
</p>
<p>
    If you do not wish complete the training right now,
    <a href="<?= Url::to([$this->context->getHomeUrl()]) ?>">click here</a> to return to Premium Services.
</p>
<p>
    You have 2 training options. Watch our FREE web-based training session here:
    <b><a href="http://gosolo1.centra.com/main/User/GuestPlayback.jhtml?s_guid=0000004a2dd400000108fcd01f43ab68" target="_new">Launch OT Training</a></b> (Recommended).
</p>
<p>
    Or read the detailed instructions below.
</p>
<hr>
<h3>Opportunity Tracker</h3>
<p><img alt='Opportunity Tracker' src='/images/opp.gif' border=0 align=left hspace=10>Opportunity Tracker ("OT") provides a very simple and effective method for you to follow-up with your prospects, customers, clients and other contacts.  Not only does <? echo $COMPANY ?> help you save more, it can help you make more?..and KEEP MORE of the More!  Now when you entertain a new prospect, contact a current customer or client or just meet with a business associate, you can use Opportunity Tracker to maximize your business efforts.  Using Opportunity Tracker you will be reminded daily of the next email, telephone call or personal contact you need to complete in order to turn those 'Prospects' into Customers, Members, Associates, etc., as quickly as possible.
<p>Access your Opportunity Tracker through the Premium Services activity on your navigation bar.  Once in Premium Services, select 'Opportunity Tracker' under Related Activities.
<p>To populate OT, you can use Enter Transactions, Track Auto or directly enter the Opportunities' information as follow:
<ul>
    <li><b>Track Auto</b> - As you drive around to meet with prospects, customers, clients and other contacts, you will want to record that mileage in Track Auto. Once you have entered the mileage, you can quickly add their contact information or select an existing name in OT by clicking on the OT icon. Now, at the end of the day, month or year, you can see how many miles you are driving per customer or opportunity.
    <li><b>Enter Transactions</b> - Assume you have a lunch receipt as a result of meeting with a prospect, customer, clients or other contact.  Once you have entered all the information related to this expense in Enter Transactions, you can quickly add their contact information or select an existing name in OT by clicking on the OT icon. Now, at the end of the day, month or year, you can see how much you are spending on each customer or opportunity.
    <li><b>Opportunity Tracker Main Screen</b> - As you go through your day, if you think of a new prospect, customer, client or other contact you want to contact in the future, you can quickly add their name to OT by selecting Add Opportunity in the Opportunity Tracker main screen.
    <li><b>Telephone Updates</b> - This is also the area where you will record various phone conversations and follow-up requirements.  In this case, you may not have a related business expense or mileage to report, but you want to capture the details of that last conversation.  Perhaps your prospect told you they wanted to become a customer, and that they sent a check.  Record it!
</ul>
<p>As your list expands, you will be able to quickly select the Opportunity by last name by selecting the appropriate letter in the Alphabetical listing.
<p align=center><img src="/images/ot_main_500.jpg">
<p>Once Opportunity Tracker is open you will have the following additional functions listed to the right under Related Activities:
<ul>
    <li>
        <b>Run Reports</b> - From the Run Reports activity, you open the Opportunity Tracker Call Report.  You can generate and print reports to take with you on the road.
        You have the option of printing the report by the defaulted (current) date, or a date of your preference.  Through the 'Edit Preferences' function explained below,
        you can select to receive an email of your Opportunity Tracker Call Report (handy reminder) on a daily or weekly basis and for a pre-defined number of days.
    </li>
    <li>
        <b>Edit Preferences</b> - Customize your Opportunity Tracker to fit your business preferences and needs.  You can select the Font type and size, select to have Skype turned
        On or Off (if you are Skype user) and the settings for your Opportunity Tracker Call Report.  You can even identify your manager, sponsor, or upline you might want to
        routinely copy about your sales activity.
        <?
        if ($flow!="PPL"){
        ?>
    </li>
    <li>
        <b>Manage Documents</b> - Opportunity Tracker allows you to send emails to your prospects, customers and other contacts listed in OT.  Using 'Manage Documents' you can edit
        standard email templates to fit your business needs.  These stored emails are sent automatically as a follow-up to prospects and customers and can be edited or change
        on as-needed basis.
        <?
        }
        ?>
    </li>
    <li>
        <b>OT Training</b> - Click on OT Training at any time you need a refresher course on how to use OT.
    </li>
</ul>
<p>
    <i>After you finish your training, please take a few minutes now to visit the activities above.</i>
</p>
<p>
    <b>Contact Breakdown</b>
    <br>
    Use the 'Contact Breakdown' meter for a quick snapshot of your contact efforts to date.  Your prospects are always listed in Green to remind you that this is the area
    where you ultimately will grow your business.  Set a goal to always keep this number high and to turn those 'Prospects' into Customers, Members, Associates, etc.,
    as quickly as possible.  This meter gives you valuable information about the successes of you prospecting efforts, giving you a 'Total Contacts'
    listed, and the current status of each.
</p>
<p>
    <b>2006 Success Meter</b>
    <br>
    Use the '2006 Success Meter' to quickly determine which sales materials give you the 'greatest successes'.  This meter will help you stay focused on the sales activities
    that matter the most.
</p>
<p>
    <b>Your list of Opportunities</b>
    <br>
    The list of Opportunities will give you, at a quick glance, valuable information on each Opportunity.  This includes the date Last Contacted, date of next ToDo, Status of Opportunity,
    and Classification (priority).  After you enter each new Opportunity you will be able to edit, track history, or delete the Opportunity by clicking on the applicable icon next to the
    name.
</p>
<ul>
    <li>
        <b>Edit</b> - Click on the 'Edit Pencil' <img src="/images/edit.png" border=0> to see your ToDo list or record new contact information for that Opportunity.
        From here, you can also review or delete each ToDo listed. To edit a ToDo, simply delete the old ToDo and create a new one with the updated information.
    </li>
    <li>
        <b>History</b> - A click on the 'History' <img src="/images/history.gif" border=0> button will open a list of all the past events created for the selected Opportunity.
        From here, you can review or delete each History item listed. To change a History item, simply delete the old item and generate a new one with the updated information.
    </li>
    <li>
        <b>Delete</b> - You can quickly delete all information related to any Opportunity by clicking on the <img src="/images/delete.png" border=0> button.  Be careful!
        This will delete all information entered to date.  You will be asked to confirm you selection to delete all information.
    </li>
</ul>

<b>Look for more up coming training for Opportunity Tracker. In the meantime, we wish you much success!</b>

<?php
    $form = ActiveForm::begin([
        'action' => Url::to(['tracker-enable'])
    ]);

    echo $form->field($model, 'flow')
         ->hiddenInput(['value' => $flow])
        ->label(false);

    echo Html::submitButton('I am ready to go!', [
        'class' => 'btn btn-success'
    ]);
    $form::end();
?>